### ISSUE TITLE
Problem when tags are comma-separated but not with whitespace

### ISSUE THREAD

**Issue by q2apro** [svivian/q2a-tagging-tools#13]
I ran into a problem, first the plugin works correctly on the ask page, after correcting the tags and having them without whitespace, the splitting for the var tags does not work anymore. 

	tags = $("#tags").val().split(" ");

I fixed it in qa-tt-layer.php like that: 

	'function qa_tag_verify()',
	'{
		var tags;
		if( $("#tags").val().indexOf(\' \') >= 0 ) {
			tags = $("#tags").val().split(" ");
		}
		else if($("#tags").val().indexOf(\',\') >= 0) {
			tags = $("#tags").val().split(",");
		}
		var alltags = ","+qa_tags_complete+",";',
		// ...

Hope that helps.

**Comment by svivian** [comment]
I made a change that bases the `split()` off the Q2A option you have set. Let me know if that works for you.
