### ISSUE TITLE
Heavy bug: When tags are capitalized plugin rejects the posting.

### ISSUE THREAD

**Issue by q2apro** [svivian/q2a-tagging-tools#14]
I am using "Prevent new users from creating new tags", just now a user informed me that he cannot post questions. I investigated that and found out that he was using capitalized tags. In German and other languages you capitalize the first letter of a noun. 

This must be corrected, urgently :)

Fix proposal: 

https://github.com/svivian/q2a-tagging-tools/blob/master/qa-tt-layer.php#L23

	'		if (tags[i].length > 0 && alltags.indexOf(","+tags[i]+",") == -1) {',

to:

	'		if (tags[i].length > 0 && alltags.indexOf(","+tags[i].toLowerCase()+",") == -1) {',

**Comment by svivian** [comment]
Thanks for the bug report, this is now fixed.
