### ISSUE TITLE
Feature Request: A way to delete a tag instead of changing it to something else

### ISSUE THREAD

**Issue by gurjyot** [svivian/q2a-tagging-tools#15]
I know the main work of this plugin is to change one tag to another but as the name of the plugin is "tagging tools" so I thought it would be good to ask this feature in this plugin only.
Let me take an example, I need to delete a tag which is not related to my website's niche but many users have used it in their questions. Now I cannot rename change that tag to something else because it is completely useless for my website. 
So it would be good to if admins or moderators can delete a tag instead of just changing it. Because it is very difficult edit each and every question and remove that tag. 
And most importantly I have just talked about one tag, there are around 3 dozen tags which I need to remove.
I have also raised a question in Q2A, I hope you would respond to this soon.
http://question2answer.org/qa/47378

**Comment by svivian** [comment]
This is already possible. In the "Tag Synonyms" box, put a tag in a line on its own. Then when someone uses that tag it will be deleted.

**Comment by gurjyot** [comment]
Wow... I never knew this could work like that. Neither you mentioned anywhere that this plugin can also be used like that. 
I think you should add this feature in Readme file and the way it can be done. And the same should also be done in Q2A as this is also an important feature that this plugin is fulfilling.

**Comment by svivian** [comment]
It is listed under "Installation & Usage", point 4. But maybe it's not clear.

**Comment by gurjyot** [comment]
Actually "Installation and Usage" is passed by me as I thought it is information about how to install this plugin and how to use it.
It would be good if you make a "Features" heading and under that list all the features that this plugin has. This plugin has proved to be really helpful to me for taking care of most tags related problems.
Thanks again for such a useful plugin... :)
