### ISSUE TITLE
Big failure validations new question !

### ISSUE THREAD

**Issue by steam1** [svivian/q2a-tagging-tools#17]
Hi,
When plugin is enabled and the registred user submit new question without filling the form fields fault database sql and error page is showing:
A question2answer database query failed when generating this page! 
A full description of full failure is available in the web server's error log file. 

Error SQL from logs:
MySQL server version for the right syntax to use near ')' at line 1 - Query: SELECT word, tagcount FROM qa_words WHERE word IN ()

Thanks.

**Comment by svivian** [comment]
Finally fixed this! Sorry for the delay.
