### ISSUE TITLE
Undefined index: tags in qa-tagging-tools.php on line 21

### ISSUE THREAD

**Issue by q2apro** [svivian/q2a-tagging-tools#20]
After you hide a question, and decide to edit this question, the tags are not showing up below the editor. 

After submit the error message appears: 

> Undefined index: tags in qa-tagging-tools.php on line 21

Obviously because they are not submitted (probably removed from q2a core before).

Needs a fix.

**Comment by svivian** [comment]
How are you editing the question while hidden? There is no edit button.

**Comment by q2apro** [comment]
Weird, for me there is an edit button.

**Comment by svivian** [comment]
Is that the same for all questions? Do you have a plugin that's adding the button? Or maybe there's a specific situation it appears depending on the conditions of it being hidden (manually or flagged or rejected) or your user level?

**Comment by q2apro** [comment]
I am pretty sure this comes from the userrules override plugin: https://github.com/q2apro/q2apro-userrules/blob/master/q2apro-userrules-overrides.php
