### ISSUE TITLE
Catch if one tag is accidentally used two times

### ISSUE THREAD

**Issue by q2apro** [svivian/q2a-tagging-tools#25]
If the admin user enters:

`tag1,tag1`

Then the plugin stops working.

This happened to me accidentally, and I guess I am not the only one.

**Comment by svivian** [comment]
Can you be more specific? What exactly stops working? I tried asking a question with duplicate tags and it went through fine when I was logged in as admin. When I tried with a low-points user, the message about using existing tags came up as it should.

**Comment by svivian** [comment]
Thanks for reporting, now fixed.
