### ISSUE TITLE
Preventing new users from creating new tags forced regardless of settings

### ISSUE THREAD

**Issue by pedjas** [svivian/q2a-tagging-tools#26]
Plugin option offers option Prevent new users from creating new tags . If checked, plugin checks if user has specified number points to allow him crate new tag.

Option to set number of points criteria is hidden if this option is unchecked.

However, even if option is unchecked number of points is checked and user is not allowed to create tag.

On question save user gets message: You need 100 points to create new tags.

To fix this, admin has to enable option to get access to number of points set and then set number of points to zero (0) to actually disable this check.

This should be fixed in manner that makes it obvious: if user unchecks option it should not work at all.

By searching for solution I found out that this Prevent new users from creating new tags actually just turns on and off Javascript that initiates check while editing question, but not server side check.

In that case, it is advisable that option is rephrased to clarify that and to make points limit setting field visible regardless of this option state.

**Comment by svivian** [comment]
Thanks, I have fixed this now.
